inherits = "rasmus"

"namespace" = "bright_white"

"variable.builtin" = "white"
"variable.parameter" = "bright_white"
"variable.other.member" = "bright_white"

"keyword.control.conditional" = "blue"
"keyword.directive" = "blue"

"type" = "bright_cyan"
"type.builtin" = "blue"
"type.enum.variant" = "bright_green"

"constructor" = "bright_blue"

"function" = "bright_blue"
"function.macro" = "bright_blue"
"function.builtin" = "bright_blue"

"comment" = "gray05"

"string" = "green"
"string.regexp" = "green"
"string.special" = "green"

"constant" = "bright_green"
"constant.builtin" = "bright_green"
"constant.numeric" = "green"
"constant.character.escape" = "yellow"
