#!/bin/bash

function copy() {
    RED=$'\033[31m'
    GREEN=$'\033[32m'
    CLEAR=$'\033[0m'

    if [ ! -e "$1" ]; then
        echo "${RED}X${CLEAR} Failed to find $1"
        return
    fi

    rm -rf "$2"
    if cp -a "$1" "$2"; then
        echo "${GREEN}O${CLEAR} Copied $1 to $2"
    else
        echo "${RED}X${CLEAR} Failed to copy $1 to $2"
    fi
}

function build_foo() {
    ROOT="$DOTFILES/fedora/starship/git_fetch_mtime"
    toolbox run -c arch-c clang "$ROOT/main.c" -o "$ROOT/git_fetch_mtime" -O2
}

list=(
    "$HOME/.config/starship"
    "$DOTFILES/fedora/starship"

    "$HOME/.config/alacritty"
    "$DOTFILES/fedora/alacritty"

    "$HOME/.bashrc.d"
    "$DOTFILES/fedora/bash/.bashrc.d"

    "$HOME/.bashrc"
    "$DOTFILES/fedora/bash/.bashrc"

    "$HOME/Documents/projects/.clang-format"
    "$DOTFILES/shared/.clang-format"

    "$HOME/.config/nvim"
    "$DOTFILES/shared/nvim"

    "$HOME/.config/yazi"
    "$DOTFILES/shared/yazi"

    "$HOME/.config/mise/conf.d"
    "$DOTFILES/shared/mise"

    "$HOME/.config/fontconfig"
    "$DOTFILES/fedora/fontconfig"

    "$DOTFILES/.git/hooks/post-merge"
    "$DOTFILES/shared/post-merge"
)

mode="${1:-push}"

if [ "$mode" = "pull" ]; then
    build_foo
    offset_from=1
    offset_to=0
else
    offset_from=0
    offset_to=1
fi

for ((i = 0; i < ${#list[@]}; i += 2)); do
    copy "${list[i + offset_from]}" "${list[i + offset_to]}"
done
